import type { ThemeDefinition } from "../types";

export const macosClassicLight: ThemeDefinition = {
  id: "macos-classic-light",
  name: "macOS Classic Light",
  description: "Classic macOS light theme with nostalgic aesthetics",
  category: "Light",
  isDark: false,
  cssVariables: {
    "--tw-primary-bg": "#ffffff",
    "--tw-editor-bg": "#ffffff",
    "--tw-secondary-bg": "#F7F7F7",
    "--tw-panel-bg": "#F9F9F9",
    "--tw-text": "#000000",
    "--tw-text-light": "#505050",
    "--tw-text-lighter": "#929292",
    "--tw-accent": "#1f6ae2",
    "--tw-border": "#D2D2D2",
    "--tw-border-variant": "#E0E0E0",
    "--tw-border-focused": "#eeeeee",
    "--tw-border-selected": "#DADADA",
    "--tw-hover": "#D0D0D0",
    "--tw-selected": "#C7DEFF",
    "--tw-statusbar-bg": "#E9E9E9",
    "--tw-titlebar-bg": "#FEFEFE",
    "--tw-tabbar-bg": "#E9E9E9",
    "--tw-tab-active-bg": "#FFFFFF",
    "--tw-tab-inactive-bg": "#E9E9E9",
    "--tw-toolbar-bg": "#FFFFFF",
    "--tw-gutter-bg": "#FFFFFF",
    "--tw-active-line-bg": "#F0F0F0",
    "--tw-line-number": "#929292",
    "--tw-active-line-number": "#000000",
    "--tw-terminal-bg": "#ffffff",
    "--tw-terminal-fg": "#000000",
    "--tw-terminal-ansi-black": "#000000",
    "--tw-terminal-ansi-red": "#C5060B",
    "--tw-terminal-ansi-green": "#277F2B",
    "--tw-terminal-ansi-yellow": "#8E7823",
    "--tw-terminal-ansi-blue": "#282BFF",
    "--tw-terminal-ansi-magenta": "#AE30C2",
    "--tw-terminal-ansi-cyan": "#00767C",
    "--tw-terminal-ansi-white": "#ffffff",
    "--tw-scrollbar-thumb": "#C8C8C8",
    "--tw-scrollbar-thumb-hover": "#C8C8C8",
    "--tw-scrollbar-track": "#ffffff",
    "--tw-warning": "#C99401",
  },
  syntaxTokens: {
    "--color-syntax-keyword": "#0433ff",
    "--color-syntax-string": "#036A07",
    "--color-syntax-number": "#0433ff",
    "--color-syntax-comment": "#007fff",
    "--color-syntax-variable": "#333333",
    "--color-syntax-function": "#0000A2",
    "--color-syntax-type": "#6f42c1",
    "--color-syntax-constant": "#C5060B",
    "--color-syntax-property": "#333333",
  },
};

export const macosClassicDark: ThemeDefinition = {
  id: "macos-classic-dark",
  name: "macOS Classic Dark",
  description: "Classic macOS dark theme with nostalgic aesthetics",
  category: "Dark",
  isDark: true,
  cssVariables: {
    "--tw-primary-bg": "#131313",
    "--tw-editor-bg": "#131313",
    "--tw-secondary-bg": "#1E1D1E",
    "--tw-panel-bg": "#1E1D1E",
    "--tw-text": "#DDDDDD",
    "--tw-text-light": "#AAAAAA",
    "--tw-text-lighter": "#777777",
    "--tw-accent": "#1f6ae2",
    "--tw-border": "#3E3E3E",
    "--tw-border-variant": "#2D2D2D",
    "--tw-border-focused": "#444444",
    "--tw-border-selected": "#3E3E3E",
    "--tw-hover": "#2C2C2C",
    "--tw-selected": "#2C2C2C",
    "--tw-statusbar-bg": "#1E1D1E",
    "--tw-titlebar-bg": "#1E1D1E",
    "--tw-tabbar-bg": "#1E1D1E",
    "--tw-tab-active-bg": "#131313",
    "--tw-tab-inactive-bg": "#1E1D1E",
    "--tw-toolbar-bg": "#131313",
    "--tw-gutter-bg": "#131313",
    "--tw-active-line-bg": "#2A2A2A",
    "--tw-line-number": "#636363",
    "--tw-active-line-number": "#DDDDDD",
    "--tw-terminal-bg": "#131313",
    "--tw-terminal-fg": "#CACCCA",
    "--tw-terminal-ansi-black": "#1E1D1E",
    "--tw-terminal-ansi-red": "#E1606C",
    "--tw-terminal-ansi-green": "#4EA93C",
    "--tw-terminal-ansi-yellow": "#D0A215",
    "--tw-terminal-ansi-blue": "#2774FF",
    "--tw-terminal-ansi-magenta": "#C254C9",
    "--tw-terminal-ansi-cyan": "#009B94",
    "--tw-terminal-ansi-white": "#ffffff",
    "--tw-scrollbar-thumb": "#474747",
    "--tw-scrollbar-thumb-hover": "#474747",
    "--tw-scrollbar-track": "#131313",
    "--tw-warning": "#D0A215",
  },
  syntaxTokens: {
    "--color-syntax-keyword": "#0F6EEF",
    "--color-syntax-string": "#18AB46",
    "--color-syntax-number": "#0F6EEF",
    "--color-syntax-comment": "#3384FF",
    "--color-syntax-variable": "#DDDDDD",
    "--color-syntax-function": "#3B3FFF",
    "--color-syntax-type": "#8E73C8",
    "--color-syntax-constant": "#E1606C",
    "--color-syntax-property": "#DDDDDD",
  },
};
