import type { ThemeDefinition } from "../types";

export const oneDarkProMonokaiDarker: ThemeDefinition = {
  id: "one-dark-pro-monokai-darker",
  name: "One Dark Pro Monokai Darker",
  description: "One Dark Pro with Monokai inspiration and darker colors",
  category: "Dark",
  isDark: true,
  cssVariables: {
    "--tw-primary-bg": "#121212",
    "--tw-editor-bg": "#121212",
    "--tw-secondary-bg": "#181a1f",
    "--tw-panel-bg": "#181a1f",
    "--tw-text": "#bbbbbb",
    "--tw-text-light": "#969696",
    "--tw-text-lighter": "#5c6370",
    "--tw-accent": "#528bff",
    "--tw-border": "#181a1f",
    "--tw-border-variant": "#181a1f",
    "--tw-border-focused": "#181a1f",
    "--tw-border-selected": "#181a1f",
    "--tw-hover": "#121212",
    "--tw-selected": "#121212",
    "--tw-statusbar-bg": "#020202",
    "--tw-titlebar-bg": "#020202",
    "--tw-tabbar-bg": "#181a1f",
    "--tw-tab-active-bg": "#121212",
    "--tw-tab-inactive-bg": "#181a1f",
    "--tw-toolbar-bg": "#121212",
    "--tw-gutter-bg": "#121212",
    "--tw-active-line-bg": "#1d1f23",
    "--tw-line-number": "#495162",
    "--tw-active-line-number": "#bbbbbb",
    "--tw-terminal-bg": "#121212",
    "--tw-terminal-fg": "#bbbbbb",
    "--tw-terminal-ansi-black": "#121212",
    "--tw-terminal-ansi-red": "#e06c75",
    "--tw-terminal-ansi-green": "#98c379",
    "--tw-terminal-ansi-yellow": "#e5c07b",
    "--tw-terminal-ansi-blue": "#61afef",
    "--tw-terminal-ansi-magenta": "#c678dd",
    "--tw-terminal-ansi-cyan": "#56b6c2",
    "--tw-terminal-ansi-white": "#bbbbbb",
    "--tw-scrollbar-thumb": "#4e5666",
    "--tw-scrollbar-thumb-hover": "#5a6375",
    "--tw-scrollbar-track": "#121212",
    "--tw-error": "#704040",
    "--tw-warning": "#407040",
    "--tw-info": "#707040",
    "--tw-hint": "#969696",
  },
  syntaxTokens: {
    "--color-syntax-keyword": "#e06c75",
    "--color-syntax-string": "#e5c07b",
    "--color-syntax-number": "#c678dd",
    "--color-syntax-comment": "#5c6370",
    "--color-syntax-variable": "#e06c75",
    "--color-syntax-function": "#98c379",
    "--color-syntax-type": "#61afef",
    "--color-syntax-constant": "#56b6c2",
    "--color-syntax-property": "#98c379",
    "--color-syntax-operator": "#e06c75",
    "--color-syntax-punctuation": "#bbbbbb",
  },
};
