import type { ThemeDefinition } from "../types";

export const oneDarkPro: ThemeDefinition = {
  id: "one-dark-pro",
  name: "One Dark Pro",
  description: "Atom's iconic One Dark theme, enhanced",
  category: "Dark",
  isDark: true,
  cssVariables: {
    "--tw-primary-bg": "#23272e",
    "--tw-editor-bg": "#23272e",
    "--tw-secondary-bg": "#1e2227",
    "--tw-panel-bg": "#23272e",
    "--tw-text": "#abb2bf",
    "--tw-border": "#3e4452",
    "--tw-border-variant": "#3e4452",
    "--tw-border-focused": "#3e4452",
    "--tw-border-selected": "#3e4452",
    "--tw-hover": "#2c313a",
    "--tw-selected": "#2c313a",
    "--tw-statusbar-bg": "#1e2227",
    "--tw-titlebar-bg": "#23272e",
    "--tw-tabbar-bg": "#1e2227",
    "--tw-tab-active-bg": "#23272e",
    "--tw-tab-inactive-bg": "#1e2227",
    "--tw-toolbar-bg": "#23272e",
    "--tw-gutter-bg": "#23272e",
    "--tw-active-line-bg": "#2c313c",
    "--tw-line-number": "#495162",
    "--tw-active-line-number": "#abb2bf",
    "--tw-terminal-bg": "#23272e",
    "--tw-terminal-ansi-black": "#3f4451",
    "--tw-terminal-ansi-red": "#e05561",
    "--tw-terminal-ansi-green": "#8cc265",
    "--tw-terminal-ansi-yellow": "#d18f52",
    "--tw-terminal-ansi-blue": "#4aa5f0",
    "--tw-terminal-ansi-magenta": "#c162de",
    "--tw-terminal-ansi-cyan": "#42b3c2",
    "--tw-terminal-ansi-white": "#d7dae0",
    "--tw-scrollbar-thumb": "#4e5666",
    "--tw-scrollbar-thumb-hover": "#5a6375",
    "--tw-scrollbar-track": "#23272e",
    "--tw-error": "#c24038",
    "--tw-warning": "#d19a66",
    "--tw-hint": "#7a849c",
  },
  syntaxTokens: {
    "--color-syntax-keyword": "#c678dd",
    "--color-syntax-string": "#98c379",
    "--color-syntax-number": "#d19a66",
    "--color-syntax-comment": "#7F838C",
    "--color-syntax-variable": "#e06c75",
    "--color-syntax-function": "#61afef",
    "--color-syntax-type": "#e5c07b",
    "--color-syntax-constant": "#d19a66",
    "--color-syntax-property": "#e06c75",
    "--color-syntax-operator": "#abb2bf",
    "--color-syntax-punctuation": "#abb2bf",
  },
};
