import { Moon, Sun } from "lucide-react";
import { BaseThemeExtension } from "../base-theme-extension";
import type { ThemeDefinition } from "../types";

class CatppuccinExtension extends BaseThemeExtension {
  readonly name = "Catppuccin";
  readonly version = "1.0.0";
  readonly description = "Catppuccin theme variants - warm, cozy pastel theme";

  readonly themes: ThemeDefinition[] = [
    {
      id: "catppuccin-latte",
      name: "Catppuccin Latte",
      description: "Light variant with warm, cozy colors",
      category: "Light",
      icon: <Sun size={14} />,
      isDark: false,
      cssVariables: {
        "--tw-primary-bg": "#eff1f5",
        "--tw-secondary-bg": "#e6e9ef",
        "--tw-text": "#4c4f69",
        "--tw-text-light": "#6c6f85",
        "--tw-text-lighter": "#9ca0b0",
        "--tw-border": "#bcc0cc",
        "--tw-hover": "#dce0e8",
        "--tw-selected": "#ccd0da",
        "--tw-accent": "#1e66f5",
      },
      syntaxTokens: {
        "--color-syntax-keyword": "#8839ef",
        "--color-syntax-string": "#40a02b",
        "--color-syntax-number": "#fe640b",
        "--color-syntax-comment": "#9ca0b0",
        "--color-syntax-variable": "#d20f39",
        "--color-syntax-function": "#1e66f5",
        "--color-syntax-constant": "#fe640b",
        "--color-syntax-property": "#04a5e5",
        "--color-syntax-type": "#df8e1d",
        "--color-syntax-operator": "#179299",
        "--color-syntax-punctuation": "#4c4f69",
        "--color-syntax-boolean": "#fe640b",
        "--color-syntax-null": "#fe640b",
        "--color-syntax-regex": "#40a02b",
        "--color-syntax-jsx": "#d20f39",
        "--color-syntax-jsx-attribute": "#8839ef",
      },
    },
    {
      id: "catppuccin-mocha",
      name: "Catppuccin Mocha",
      description: "Dark variant with warm, cozy colors",
      category: "Dark",
      icon: <Moon size={14} />,
      isDark: true,
      cssVariables: {
        "--tw-primary-bg": "#1e1e2e",
        "--tw-secondary-bg": "#181825",
        "--tw-text": "#cdd6f4",
        "--tw-text-light": "#bac2de",
        "--tw-text-lighter": "#a6adc8",
        "--tw-border": "#45475a",
        "--tw-hover": "#313244",
        "--tw-selected": "#45475a",
        "--tw-accent": "#89b4fa",
      },
      syntaxTokens: {
        "--color-syntax-keyword": "#cba6f7",
        "--color-syntax-string": "#a6e3a1",
        "--color-syntax-number": "#fab387",
        "--color-syntax-comment": "#6c7086",
        "--color-syntax-variable": "#f38ba8",
        "--color-syntax-function": "#89b4fa",
        "--color-syntax-constant": "#fab387",
        "--color-syntax-property": "#89dceb",
        "--color-syntax-type": "#f9e2af",
        "--color-syntax-operator": "#94e2d5",
        "--color-syntax-punctuation": "#cdd6f4",
        "--color-syntax-boolean": "#fab387",
        "--color-syntax-null": "#fab387",
        "--color-syntax-regex": "#a6e3a1",
        "--color-syntax-jsx": "#f38ba8",
        "--color-syntax-jsx-attribute": "#cba6f7",
      },
    },
    {
      id: "catppuccin-macchiato",
      name: "Catppuccin Macchiato",
      description: "Medium dark variant with balanced contrast",
      category: "Dark",
      icon: <Moon size={14} />,
      isDark: true,
      cssVariables: {
        "--tw-primary-bg": "#24273a",
        "--tw-secondary-bg": "#1e2030",
        "--tw-text": "#cad3f5",
        "--tw-text-light": "#b8c0e0",
        "--tw-text-lighter": "#a5adcb",
        "--tw-border": "#494d64",
        "--tw-hover": "#363a4f",
        "--tw-selected": "#494d64",
        "--tw-accent": "#8aadf4",
      },
      syntaxTokens: {
        "--color-syntax-keyword": "#c6a0f6",
        "--color-syntax-string": "#a6da95",
        "--color-syntax-number": "#f5a97f",
        "--color-syntax-comment": "#6e738d",
        "--color-syntax-variable": "#f5bde6",
        "--color-syntax-function": "#8aadf4",
        "--color-syntax-constant": "#f5a97f",
        "--color-syntax-property": "#8bd5ca",
        "--color-syntax-type": "#eed49f",
        "--color-syntax-operator": "#91d7e3",
        "--color-syntax-punctuation": "#cad3f5",
        "--color-syntax-boolean": "#f5a97f",
        "--color-syntax-null": "#f5a97f",
        "--color-syntax-regex": "#a6da95",
        "--color-syntax-jsx": "#f5bde6",
        "--color-syntax-jsx-attribute": "#c6a0f6",
      },
    },
  ];
}

export const catppuccinExtension = new CatppuccinExtension();
