# Converted from Zed theme: Cursor
# Author: David C Cavalcante
# Original schema: https://zed.dev/schema/themes/v0.2.0.json

[[themes]]
id = "cursor-dark"
name = "Cursor Dark"
description = "Converted from Zed theme Cursor"
category = "Dark"
is_dark = true

[themes.css_variables]
"--tw-primary-bg" = "#1A1A1A"
"--tw-editor-bg" = "#1A1A1A"
"--tw-secondary-bg" = "#141414"
"--tw-panel-bg" = "#141414"
"--tw-text" = "#D8DEE9"
"--tw-text-light" = "#CCCCCC"
"--tw-text-lighter" = "#FFFFFF"
"--tw-text-disabled" = "#505050"
"--tw-accent" = "#FFFFFF"
"--tw-border" = "#FFFFFF"
"--tw-border-variant" = "#2A2A2A"
"--tw-border-focused" = "#88C0D0"
"--tw-border-selected" = "#88C0D0"
"--tw-hover" = "#292929"
"--tw-active" = "#404040"
"--tw-selected" = "#404040"
"--tw-statusbar-bg" = "#141414"
"--tw-titlebar-bg" = "#141414"
"--tw-tabbar-bg" = "#141414"
"--tw-tab-active-bg" = "#1A1A1A"
"--tw-tab-inactive-bg" = "#141414"
"--tw-toolbar-bg" = "#141414"
"--tw-gutter-bg" = "#1A1A1A"
"--tw-active-line-bg" = "#292929"
"--tw-line-number" = "#505050"
"--tw-active-line-number" = "#FFFFFF"
"--tw-terminal-bg" = "#141414"
"--tw-terminal-fg" = "#FFFFFF"
"--tw-terminal-ansi-black" = "#2A2A2A"
"--tw-terminal-ansi-red" = "#BF616A"
"--tw-terminal-ansi-green" = "#A3BE8C"
"--tw-terminal-ansi-yellow" = "#EBCB8B"
"--tw-terminal-ansi-blue" = "#81A1C1"
"--tw-terminal-ansi-magenta" = "#B48EAD"
"--tw-terminal-ansi-cyan" = "#88C0D0"
"--tw-terminal-ansi-white" = "#D8DEE9"
"--tw-scrollbar-thumb" = "#404040"
"--tw-scrollbar-thumb-hover" = "#404040"
"--tw-scrollbar-track" = "#1A1A1A"
"--tw-error" = "#BF616A"
"--tw-warning" = "#EBCB8B"
"--tw-success" = "#A3BE8C"
"--tw-info" = "#88C0D0"
"--tw-hint" = "#696969"

[themes.syntax_tokens]
"--color-syntax-keyword" = "#83D6C5"
"--color-syntax-string" = "#E394DC"
"--color-syntax-number" = "#EBC88D"
"--color-syntax-comment" = "#6D6D6D"
"--color-syntax-variable" = "#D6D6DD"
"--color-syntax-function" = "#EFB080"
"--color-syntax-type" = "#87C3FF"
"--color-syntax-constant" = "#FFFFFF"
"--color-syntax-property" = "#81D2CE"
"--color-syntax-operator" = "#83D6C5"
"--color-syntax-punctuation" = "#D6D6DD"

