import { Moon, Sun } from "lucide-react";
import { BaseThemeExtension } from "../base-theme-extension";
import type { ThemeDefinition } from "../types";

class GitHubExtension extends BaseThemeExtension {
  readonly name = "GitHub";
  readonly version = "1.0.0";
  readonly description = "GitHub theme variants - clean themes inspired by GitHub";

  readonly themes: ThemeDefinition[] = [
    {
      id: "github-light",
      name: "GitHub Light",
      description: "Clean light theme inspired by GitHub",
      category: "Light",
      icon: <Sun size={14} />,
      isDark: false,
      cssVariables: {
        "--tw-primary-bg": "#ffffff",
        "--tw-secondary-bg": "#f6f8fa",
        "--tw-text": "#24292f",
        "--tw-text-light": "#656d76",
        "--tw-text-lighter": "#8c959f",
        "--tw-border": "#d0d7de",
        "--tw-hover": "#f3f4f6",
        "--tw-selected": "#eaeef2",
        "--tw-accent": "#0969da",
      },
      syntaxTokens: {
        "--color-syntax-keyword": "#cf222e",
        "--color-syntax-string": "#0a3069",
        "--color-syntax-number": "#0550ae",
        "--color-syntax-comment": "#6e7781",
        "--color-syntax-variable": "#953800",
        "--color-syntax-function": "#8250df",
        "--color-syntax-constant": "#0550ae",
        "--color-syntax-property": "#953800",
        "--color-syntax-type": "#8250df",
        "--color-syntax-operator": "#cf222e",
        "--color-syntax-punctuation": "#24292f",
        "--color-syntax-boolean": "#0550ae",
        "--color-syntax-null": "#0550ae",
        "--color-syntax-regex": "#0a3069",
        "--color-syntax-jsx": "#22863a",
        "--color-syntax-jsx-attribute": "#8250df",
      },
    },
    {
      id: "github-dark",
      name: "GitHub Dark",
      description: "Dark theme inspired by GitHub Dark",
      category: "Dark",
      icon: <Moon size={14} />,
      isDark: true,
      cssVariables: {
        "--tw-primary-bg": "#0d1117",
        "--tw-secondary-bg": "#161b22",
        "--tw-text": "#e6edf3",
        "--tw-text-light": "#7d8590",
        "--tw-text-lighter": "#656d76",
        "--tw-border": "#30363d",
        "--tw-hover": "#21262d",
        "--tw-selected": "#30363d",
        "--tw-accent": "#2f81f7",
      },
      syntaxTokens: {
        "--color-syntax-keyword": "#ff7b72",
        "--color-syntax-string": "#a5d6ff",
        "--color-syntax-number": "#79c0ff",
        "--color-syntax-comment": "#8b949e",
        "--color-syntax-variable": "#ffa657",
        "--color-syntax-function": "#d2a8ff",
        "--color-syntax-constant": "#79c0ff",
        "--color-syntax-property": "#ffa657",
        "--color-syntax-type": "#4ec9b0",
        "--color-syntax-operator": "#ff7b72",
        "--color-syntax-punctuation": "#e6edf3",
        "--color-syntax-boolean": "#79c0ff",
        "--color-syntax-null": "#79c0ff",
        "--color-syntax-regex": "#a5d6ff",
        "--color-syntax-jsx": "#7ee787",
        "--color-syntax-jsx-attribute": "#d2a8ff",
      },
    },
    {
      id: "github-dark-dimmed",
      name: "GitHub Dark Dimmed",
      description: "Dimmed variant for reduced eye strain",
      category: "Dark",
      icon: <Moon size={14} />,
      isDark: true,
      cssVariables: {
        "--tw-primary-bg": "#22272e",
        "--tw-secondary-bg": "#2d333b",
        "--tw-text": "#adbac7",
        "--tw-text-light": "#768390",
        "--tw-text-lighter": "#636e7b",
        "--tw-border": "#444c56",
        "--tw-hover": "#373e47",
        "--tw-selected": "#444c56",
        "--tw-accent": "#539bf5",
      },
      syntaxTokens: {
        "--color-syntax-keyword": "#f47067",
        "--color-syntax-string": "#96d0ff",
        "--color-syntax-number": "#6cb6ff",
        "--color-syntax-comment": "#768390",
        "--color-syntax-variable": "#f69d50",
        "--color-syntax-function": "#dcbdfb",
        "--color-syntax-constant": "#6cb6ff",
        "--color-syntax-property": "#f69d50",
        "--color-syntax-type": "#dcbdfb",
        "--color-syntax-operator": "#f47067",
        "--color-syntax-punctuation": "#adbac7",
        "--color-syntax-boolean": "#6cb6ff",
        "--color-syntax-null": "#6cb6ff",
        "--color-syntax-regex": "#96d0ff",
        "--color-syntax-jsx": "#8ddb8c",
        "--color-syntax-jsx-attribute": "#dcbdfb",
      },
    },
  ];
}

export const githubExtension = new GitHubExtension();