# Converted from Zed theme: macOS Classic
# Author: huacnlee
# Original schema: https://zed.dev/schema/themes/v0.1.0.json

[[themes]]
id = "macos-classic-light"
name = "macOS Classic Light"
description = "Converted from Zed theme macOS Classic"
category = "Light"
is_dark = false

[themes.css_variables]
"--tw-primary-bg" = "#ffffff"
"--tw-editor-bg" = "#ffffff"
"--tw-secondary-bg" = "#F9F9F9"
"--tw-panel-bg" = "#F9F9F9"
"--tw-text" = "#000000"
"--tw-text-light" = "#505050"
"--tw-text-lighter" = "#929292"
"--tw-accent" = "#1f6ae2"
"--tw-border" = "#D2D2D2"
"--tw-border-variant" = "#E0E0E0"
"--tw-border-focused" = "#eeeeee"
"--tw-border-selected" = "#DADADA"
"--tw-hover" = "#D0D0D0"
"--tw-selected" = "#C7DEFF"
"--tw-statusbar-bg" = "#E9E9E9"
"--tw-titlebar-bg" = "#FEFEFE"
"--tw-tabbar-bg" = "#E9E9E9"
"--tw-tab-active-bg" = "#FFFFFF"
"--tw-tab-inactive-bg" = "#E9E9E9"
"--tw-toolbar-bg" = "#FFFFFF"
"--tw-gutter-bg" = "#FFFFFF"
"--tw-active-line-bg" = "#F0F0F0"
"--tw-line-number" = "#929292"
"--tw-active-line-number" = "#000000"
"--tw-terminal-bg" = "#ffffff"
"--tw-terminal-fg" = "#000000"
"--tw-terminal-ansi-black" = "#000000"
"--tw-terminal-ansi-red" = "#C5060B"
"--tw-terminal-ansi-green" = "#277F2B"
"--tw-terminal-ansi-yellow" = "#8E7823"
"--tw-terminal-ansi-blue" = "#282BFF"
"--tw-terminal-ansi-magenta" = "#AE30C2"
"--tw-terminal-ansi-cyan" = "#00767C"
"--tw-terminal-ansi-white" = "#ffffff"
"--tw-scrollbar-thumb" = "#C8C8C8"
"--tw-scrollbar-thumb-hover" = "#C8C8C8"
"--tw-scrollbar-track" = "#ffffff"
"--tw-warning" = "#C99401"

[themes.syntax_tokens]
"--color-syntax-keyword" = "#0433ff"
"--color-syntax-string" = "#036A07"
"--color-syntax-number" = "#0433ff"
"--color-syntax-comment" = "#007fff"
"--color-syntax-variable" = "#333333"
"--color-syntax-function" = "#0000A2"
"--color-syntax-type" = "#6f42c1"
"--color-syntax-constant" = "#C5060B"
"--color-syntax-property" = "#333333"


[[themes]]
id = "macos-classic-dark"
name = "macOS Classic Dark"
description = "Converted from Zed theme macOS Classic"
category = "Dark"
is_dark = true

[themes.css_variables]
"--tw-primary-bg" = "#131313"
"--tw-editor-bg" = "#131313"
"--tw-secondary-bg" = "#1E1D1E"
"--tw-panel-bg" = "#1E1D1E"
"--tw-text" = "#DDDDDD"
"--tw-text-light" = "#9E9E9E"
"--tw-border" = "#404040"
"--tw-border-variant" = "#3A3A3A"
"--tw-border-focused" = "#3A3A3A"
"--tw-border-selected" = "#3A3A3A"
"--tw-hover" = "#353436"
"--tw-active" = "#353436"
"--tw-selected" = "#353436"
"--tw-statusbar-bg" = "#272727"
"--tw-titlebar-bg" = "#323232"
"--tw-tabbar-bg" = "#232323"
"--tw-tab-active-bg" = "#131313"
"--tw-tab-inactive-bg" = "#232323"
"--tw-toolbar-bg" = "#131313"
"--tw-gutter-bg" = "#131313"
"--tw-active-line-bg" = "#272727"
"--tw-line-number" = "#8F8F8F"
"--tw-active-line-number" = "#DDDDDD"
"--tw-terminal-ansi-black" = "#E8E4CF"
"--tw-terminal-ansi-red" = "#A8473B"
"--tw-terminal-ansi-green" = "#76BA53"
"--tw-terminal-ansi-yellow" = "#E1D797"
"--tw-terminal-ansi-blue" = "#082190"
"--tw-terminal-ansi-magenta" = "#AE30C2"
"--tw-terminal-ansi-cyan" = "#3DB6B0"
"--tw-terminal-ansi-white" = "#131313"
"--tw-scrollbar-thumb" = "#4C4D4D"
"--tw-scrollbar-thumb-hover" = "#4C4D4D"
"--tw-scrollbar-track" = "#131313"

[themes.syntax_tokens]
"--color-syntax-keyword" = "#c28b12"
"--color-syntax-string" = "#62BA46"
"--color-syntax-number" = "#E1D797"
"--color-syntax-comment" = "#9E9E9E"
"--color-syntax-function" = "#fdd888"
"--color-syntax-type" = "#c75828"
"--color-syntax-constant" = "#E1D797"
"--color-syntax-property" = "#CACCCA"

