# Converted from Zed theme: One
# Author: Zed Industries
# Original schema: https://zed.dev/schema/themes/v0.2.0.json

[[themes]]
id = "one-dark"
name = "One Dark"
description = "Converted from Zed theme One"
category = "Dark"
is_dark = true

[themes.css_variables]
"--tw-primary-bg" = "#3b414d"
"--tw-editor-bg" = "#282c33"
"--tw-secondary-bg" = "#2f343e"
"--tw-panel-bg" = "#2f343e"
"--tw-text" = "#acb2be"
"--tw-text-light" = "#a9afbc"
"--tw-text-lighter" = "#878a98"
"--tw-text-disabled" = "#878a98"
"--tw-accent" = "#74ade8"
"--tw-border" = "#464b57"
"--tw-border-variant" = "#363c46"
"--tw-border-focused" = "#47679e"
"--tw-border-selected" = "#293b5b"
"--tw-hover" = "#363c46"
"--tw-active" = "#454a56"
"--tw-selected" = "#454a56"
"--tw-statusbar-bg" = "#3b414d"
"--tw-titlebar-bg" = "#3b414d"
"--tw-tabbar-bg" = "#2f343e"
"--tw-tab-active-bg" = "#282c33"
"--tw-tab-inactive-bg" = "#2f343e"
"--tw-toolbar-bg" = "#282c33"
"--tw-gutter-bg" = "#282c33"
"--tw-active-line-bg" = "#2f343e"
"--tw-line-number" = "#4e5a5f"
"--tw-active-line-number" = "#d0d4da"
"--tw-terminal-bg" = "#282c33"
"--tw-terminal-fg" = "#dce0e5"
"--tw-terminal-ansi-black" = "#282c33"
"--tw-terminal-ansi-red" = "#d07277"
"--tw-terminal-ansi-green" = "#a1c181"
"--tw-terminal-ansi-yellow" = "#dec184"
"--tw-terminal-ansi-blue" = "#74ade8"
"--tw-terminal-ansi-magenta" = "#b477cf"
"--tw-terminal-ansi-cyan" = "#6eb4bf"
"--tw-terminal-ansi-white" = "#dce0e5"
"--tw-scrollbar-thumb" = "#c8ccd4"
"--tw-scrollbar-thumb-hover" = "#363c46"
"--tw-scrollbar-track" = "#000000"
"--tw-error" = "#d07277"
"--tw-warning" = "#dec184"
"--tw-success" = "#a1c181"
"--tw-info" = "#74ade8"
"--tw-hint" = "#788ca6"
"--tw-git-added" = "#27a657"
"--tw-git-modified" = "#d3b020"
"--tw-git-deleted" = "#e06c76"

[themes.syntax_tokens]
"--color-syntax-keyword" = "#b477cf"
"--color-syntax-string" = "#a1c181"
"--color-syntax-number" = "#bf956a"
"--color-syntax-comment" = "#5d636f"
"--color-syntax-variable" = "#acb2be"
"--color-syntax-function" = "#73ade9"
"--color-syntax-type" = "#6eb4bf"
"--color-syntax-constant" = "#dfc184"
"--color-syntax-property" = "#d07277"
"--color-syntax-operator" = "#6eb4bf"
"--color-syntax-punctuation" = "#acb2be"


[[themes]]
id = "one-light"
name = "One Light"
description = "Converted from Zed theme One"
category = "Light"
is_dark = false

[themes.css_variables]
"--tw-primary-bg" = "#dcdcdd"
"--tw-editor-bg" = "#fafafa"
"--tw-secondary-bg" = "#ebebec"
"--tw-panel-bg" = "#ebebec"
"--tw-text" = "#242529"
"--tw-text-light" = "#58585a"
"--tw-text-lighter" = "#7e8086"
"--tw-text-disabled" = "#7e8086"
"--tw-accent" = "#5c78e2"
"--tw-border" = "#c9c9ca"
"--tw-border-variant" = "#dfdfe0"
"--tw-border-focused" = "#7d82e8"
"--tw-border-selected" = "#cbcdf6"
"--tw-hover" = "#dfdfe0"
"--tw-active" = "#cacaca"
"--tw-selected" = "#cacaca"
"--tw-statusbar-bg" = "#dcdcdd"
"--tw-titlebar-bg" = "#dcdcdd"
"--tw-tabbar-bg" = "#ebebec"
"--tw-tab-active-bg" = "#fafafa"
"--tw-tab-inactive-bg" = "#ebebec"
"--tw-toolbar-bg" = "#fafafa"
"--tw-gutter-bg" = "#fafafa"
"--tw-active-line-bg" = "#ebebec"
"--tw-line-number" = "#b4b4bb"
"--tw-active-line-number" = "#44454b"
"--tw-terminal-bg" = "#fafafa"
"--tw-terminal-fg" = "#242529"
"--tw-terminal-ansi-black" = "#242529"
"--tw-terminal-ansi-red" = "#d36151"
"--tw-terminal-ansi-green" = "#669f59"
"--tw-terminal-ansi-yellow" = "#dec184"
"--tw-terminal-ansi-blue" = "#5c78e2"
"--tw-terminal-ansi-magenta" = "#984ea5"
"--tw-terminal-ansi-cyan" = "#3a82b7"
"--tw-terminal-ansi-white" = "#fafafa"
"--tw-scrollbar-thumb" = "#383a41"
"--tw-scrollbar-thumb-hover" = "#dfdfe0"
"--tw-scrollbar-track" = "#000000"
"--tw-error" = "#d36151"
"--tw-warning" = "#a48819"
"--tw-success" = "#669f59"
"--tw-info" = "#5c78e2"
"--tw-hint" = "#7274a7"
"--tw-git-added" = "#27a657"
"--tw-git-modified" = "#d3b020"
"--tw-git-deleted" = "#e06c76"

[themes.syntax_tokens]
"--color-syntax-keyword" = "#a449ab"
"--color-syntax-string" = "#649f57"
"--color-syntax-number" = "#ad6e25"
"--color-syntax-comment" = "#a2a3a7"
"--color-syntax-variable" = "#242529"
"--color-syntax-function" = "#5b79e3"
"--color-syntax-type" = "#3882b7"
"--color-syntax-constant" = "#c18401"
"--color-syntax-property" = "#d3604f"
"--color-syntax-operator" = "#3882b7"
"--color-syntax-punctuation" = "#242529"

