# Converted from Zed theme: supaglass
# Author: Piyush Kacha <piyushkacha75@gmail.com>
# Original schema: https://zed.dev/schema/themes/v0.2.0.json

[[themes]]
id = "supaglass-dark"
name = "supaglass"
description = "Converted from Zed theme supaglass"
category = "Dark"
is_dark = true

[themes.css_variables]
"--tw-primary-bg" = "#1a1a1a"
"--tw-editor-bg" = "#1a1a1a"
"--tw-secondary-bg" = "#151515"
"--tw-panel-bg" = "#151515"
"--tw-text" = "#c0caf5"
"--tw-text-light" = "#aaaaaa"
"--tw-text-lighter" = "#aaaaaa"
"--tw-text-disabled" = "#555555"
"--tw-accent" = "#3ecf8e"
"--tw-border" = "#0f0f0f"
"--tw-border-variant" = "#0f0f0f"
"--tw-border-focused" = "#3ecf8e"
"--tw-border-selected" = "#0f0f0f"
"--tw-hover" = "#3ecf8e"
"--tw-active" = "#3ecf8e"
"--tw-selected" = "#3ecf8e"
"--tw-statusbar-bg" = "#151515"
"--tw-titlebar-bg" = "#151515"
"--tw-tabbar-bg" = "#151515"
"--tw-tab-active-bg" = "#3ecf8e"
"--tw-tab-inactive-bg" = "#151515"
"--tw-toolbar-bg" = "#151515"
"--tw-gutter-bg" = "#1a1a1a"
"--tw-active-line-bg" = "#202020"
"--tw-line-number" = "#444444"
"--tw-active-line-number" = "#d4d4d4"
"--tw-terminal-bg" = "#1a1a1a"
"--tw-terminal-fg" = "#d4d4d4"
"--tw-terminal-ansi-black" = "#333333"
"--tw-terminal-ansi-red" = "#f7768e"
"--tw-terminal-ansi-green" = "#2e9b6a"
"--tw-terminal-ansi-yellow" = "#e0af68"
"--tw-terminal-ansi-blue" = "#7aa2f7"
"--tw-terminal-ansi-magenta" = "#bb9af7"
"--tw-terminal-ansi-cyan" = "#41a6b5"
"--tw-terminal-ansi-white" = "#888888"
"--tw-scrollbar-thumb" = "#555555"
"--tw-scrollbar-thumb-hover" = "#555555"
"--tw-scrollbar-track" = "#1a1a1a"
"--tw-error" = "#f7768e"
"--tw-warning" = "#e0af68"
"--tw-success" = "#3ecf8e"
"--tw-info" = "#0da0ba"
"--tw-hint" = "#5f6996"
"--tw-git-added" = "#3ecf8e"
"--tw-git-modified" = "#e0af68"
"--tw-git-deleted" = "#f7768e"

[themes.syntax_tokens]
"--color-syntax-keyword" = "#9d7cd8"
"--color-syntax-string" = "#9ece6a"
"--color-syntax-number" = "#ff9e64"
"--color-syntax-comment" = "#565f89"
"--color-syntax-variable" = "#c0caf5"
"--color-syntax-function" = "#7dcfff"
"--color-syntax-type" = "#2ac3de"
"--color-syntax-constant" = "#bb9af7"
"--color-syntax-property" = "#73daca"
"--color-syntax-operator" = "#89ddff"
"--color-syntax-punctuation" = "#a9b1d6"

