import { Moon } from "lucide-react";
import { BaseThemeExtension } from "../base-theme-extension";
import type { ThemeDefinition } from "../types";

class TokyoNightExtension extends BaseThemeExtension {
  readonly name = "Tokyo Night";
  readonly version = "1.0.0";
  readonly description =
    "Tokyo Night theme variants - a clean, dark theme inspired by the neon lights of Tokyo";

  readonly themes: ThemeDefinition[] = [
    {
      id: "tokyo-night",
      name: "Tokyo Night",
      description: "Original Tokyo Night theme with deep blues and vibrant accents",
      category: "Dark",
      icon: <Moon size={14} />,
      isDark: true,
      cssVariables: {
        "--tw-primary-bg": "#1a1b26",
        "--tw-secondary-bg": "#24283b",
        "--tw-text": "#c0caf5",
        "--tw-text-light": "#9aa5ce",
        "--tw-text-lighter": "#565f89",
        "--tw-border": "#414868",
        "--tw-hover": "#2f3549",
        "--tw-selected": "#364a82",
        "--tw-accent": "#7aa2f7",
      },
      syntaxTokens: {
        "--color-syntax-keyword": "#bb9af7",
        "--color-syntax-string": "#9ece6a",
        "--color-syntax-number": "#ff9e64",
        "--color-syntax-comment": "#565f89",
        "--color-syntax-variable": "#f7768e",
        "--color-syntax-function": "#7aa2f7",
        "--color-syntax-constant": "#ff9e64",
        "--color-syntax-property": "#7aa2f7",
        "--color-syntax-type": "#0db9d7",
        "--color-syntax-operator": "#89ddff",
        "--color-syntax-punctuation": "#c0caf5",
        "--color-syntax-boolean": "#ff9e64",
        "--color-syntax-null": "#ff9e64",
        "--color-syntax-regex": "#b4f9f8",
        "--color-syntax-jsx": "#f7768e",
        "--color-syntax-jsx-attribute": "#bb9af7",
      },
    },
    {
      id: "tokyo-night-storm",
      name: "Tokyo Night Storm",
      description: "Darker variant with stormy atmosphere",
      category: "Dark",
      icon: <Moon size={14} />,
      isDark: true,
      cssVariables: {
        "--tw-primary-bg": "#24283b",
        "--tw-secondary-bg": "#2f3549",
        "--tw-text": "#c0caf5",
        "--tw-text-light": "#9aa5ce",
        "--tw-text-lighter": "#545c7e",
        "--tw-border": "#3b4261",
        "--tw-hover": "#414868",
        "--tw-selected": "#364a82",
        "--tw-accent": "#7aa2f7",
      },
      syntaxTokens: {
        "--color-syntax-keyword": "#bb9af7",
        "--color-syntax-string": "#9ece6a",
        "--color-syntax-number": "#ff9e64",
        "--color-syntax-comment": "#545c7e",
        "--color-syntax-variable": "#f7768e",
        "--color-syntax-function": "#7aa2f7",
        "--color-syntax-constant": "#ff9e64",
        "--color-syntax-property": "#7aa2f7",
        "--color-syntax-type": "#0db9d7",
        "--color-syntax-operator": "#89ddff",
        "--color-syntax-punctuation": "#c0caf5",
        "--color-syntax-boolean": "#ff9e64",
        "--color-syntax-null": "#ff9e64",
        "--color-syntax-regex": "#b4f9f8",
        "--color-syntax-jsx": "#f7768e",
        "--color-syntax-jsx-attribute": "#bb9af7",
      },
    },
    {
      id: "tokyo-night-moon",
      name: "Tokyo Night Moon",
      description: "Cooler variant with moonlit tones",
      category: "Dark",
      icon: <Moon size={14} />,
      isDark: true,
      cssVariables: {
        "--tw-primary-bg": "#222436",
        "--tw-secondary-bg": "#2f334d",
        "--tw-text": "#c8d3f5",
        "--tw-text-light": "#a9b1d6",
        "--tw-text-lighter": "#636da6",
        "--tw-border": "#444a73",
        "--tw-hover": "#3b4261",
        "--tw-selected": "#3654a7",
        "--tw-accent": "#82aaff",
      },
      syntaxTokens: {
        "--color-syntax-keyword": "#fca7ea",
        "--color-syntax-string": "#c3e88d",
        "--color-syntax-number": "#ff966c",
        "--color-syntax-comment": "#636da6",
        "--color-syntax-variable": "#ff757f",
        "--color-syntax-function": "#82aaff",
        "--color-syntax-constant": "#ff966c",
        "--color-syntax-property": "#82aaff",
        "--color-syntax-type": "#86e1fc",
        "--color-syntax-operator": "#89ddff",
        "--color-syntax-punctuation": "#c8d3f5",
        "--color-syntax-boolean": "#ff966c",
        "--color-syntax-null": "#ff966c",
        "--color-syntax-regex": "#c3e88d",
        "--color-syntax-jsx": "#ff757f",
        "--color-syntax-jsx-attribute": "#fca7ea",
      },
    },
  ];
}

export const tokyoNightExtension = new TokyoNightExtension();
